tasks:
   - source: vectorizer.py
     name: vectorizer
     product:
       nb: output/vectorizer.ipynb
       vectorizer: output/vectorizer.pkl
       vocab: output/vocab.pkl
     params:
       random_seed: 42

   - source: vectorizer_svd.py
     name: vectorizer_svd
     product:
       nb: output/vectorizer_svd.ipynb
       vectorizer: output/vectorizer_svd.pkl
       vocab: output/vocab_svd.pkl
     params:
       random_seed: 42

   - source: vectorizer_spacy.py
     name: vectorizer_spacy
     product:
       nb: output/vectorizer_spacy.ipynb
       vectorizer: output/vectorizer_spacy.pkl
       vocab: output/vocab_spacy.pkl
       stopwords: output/stopwords_spacy.csv
     params:
       random_seed: 42

   - source: vectorizer_dense.py
     name: vectorizer_dense
     product:
       nb: output/vectorizer_dense.ipynb
     params:
       random_seed: 42

   - source: vectorizer_countVec.py
     name: vectorizer_countVec
     product:
       nb: output/vectorizer_countVec.ipynb
       vectorizer: output/vectorizer_countVec.pkl
     params:
       random_seed: 42
       
   - source: nn_classification_analysis.py
     name: nn_classification_analysis
     product:
       nb: output/nn_classification_analysis.ipynb
     params:
       epochs: 10

   - source: category_classification_models.py
     name: category_classification_models
     product:
       nb: output/category_classification_models.ipynb
       model_lr: output/model_lr.pkl
       model_rf: output/model_rf.pkl
       model_nb: output/model_nb.csv
       model_votingc: output/model_votingc.csv
     params:
       random_seed: 42

   - source: topic_modeling_disaster_type_final.py
     name: topic_modeling_disaster_type_final
     product:
       nb: output/topic_modeling_disaster_type_final.ipynb
       lda_model_earthquake: output/lda_model_earthquake.pkl
       lda_model_fire: output/lda_model_fire.pkl
       lda_model_flood: output/lda_model_flood.pkl
       lda_model_hurricane: output/lda_model_hurricane.pkl
       lda_topics_disaster_type: output/lda_topics_disaster_type.csv
     params:
       random_seed: 42

   - source: topic_modeling_disaster_type_results.py
     name: topic_modeling_disaster_type_results
     product:
       nb: output/topic_modeling_disaster_type_results.ipynb
     params:

   - source: recent_tweets.py
     name: recent_tweets_wildfire
     product:
       nb: output/recent_tweets_wildfire.ipynb
       file: output/recent_tweets_wildfire.csv
     params:
       disaster_type: Wildfire
       query: "wildfire (donate OR (death toll) OR burn OR fire OR forest OR damage)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_earthquake
     product:
       nb: output/recent_tweets_earthquake.ipynb
       file: output/recent_tweets_earthquake.csv
     params:
       disaster_type: Earthquake
       query: "earthquake (pray OR victim OR donate OR rescue OR damage OR magnitude)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_flood
     product:
       nb: output/recent_tweets_flood.ipynb
       file: output/recent_tweets_flood.csv
     params:
       disaster_type: Flood
       query: "flood (relief OR water OR donate OR (death toll) OR rescue OR destroy)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_hurricane
     product:
       nb: output/recent_tweets_hurricane.ipynb
       file: output/recent_tweets_hurricane.csv
     params:
       disaster_type: Hurricane
       query: "hurricane (donate OR storm OR cyclone OR damage OR evacuation OR destroy)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'
       
   - source: recommended_actions_upstream.py
     name: recommended_actions_upstream
     product:
       nb: output/recommended_actions_upstream.ipynb
       file: output/twitter_actions.csv
     params:
       disaster_types: ["wildfire", "flood", "earthquake"]
       action_types: ["volunteer", "donate", "evacuate"]
       language: 'en'
       limit: 500
       credentials_file: "credentials.yaml"
      
   - source: recommended_actions.py
     name: recommended_actions
     product:
       nb: output/recommended_actions.ipynb

   - source: tweets_timeline.py
     name: tweets_timeline_fire
     product:
       nb: output/tweets_timeline_fire.ipynb
     params:
       random_seed: 42
       disaster_kind: recent_tweets_wildfire

   - source: tweets_timeline.py
     name: tweets_timeline_earthquake
     product:
       nb: output/tweets_timeline_earthquake.ipynb
     params:
       random_seed: 42
       disaster_kind: recent_tweets_earthquake

   - source: tweets_timeline.py
     name: tweets_timeline_flood
     product:
       nb: output/tweets_timeline_flood.ipynb
     params:
       random_seed: 42
       disaster_kind: recent_tweets_flood

   - source: tweets_timeline.py
     name: tweets_timeline_hurricane
     product:
       nb: output/tweets_timeline_hurricane.ipynb
     params:
       random_seed: 42
       disaster_kind: recent_tweets_hurricane