tasks:
   - source: vectorizer.py
     name: vectorizer
     product:
       nb: output/vectorizer.ipynb
       vectorizer: output/vectorizer.pkl
       vocab: output/vocab.pkl
     params:
       random_seed: 42

   - source: vectorizer_svd.py
     name: vectorizer_svd
     product:
       nb: output/vectorizer_svd.ipynb
       vectorizer: output/vectorizer_svd.pkl
       vocab: output/vocab_svd.pkl
     params:
       random_seed: 42

   - source: vectorizer_spacy.py
     name: vectorizer_spacy
     product:
       nb: output/vectorizer_spacy.ipynb
       vectorizer: output/vectorizer_spacy.pkl
       vocab: output/vocab_spacy.pkl
       stopwords: output/stopwords_spacy.csv
     params:
       random_seed: 42

   - source: vectorizer_dense.py
     name: vectorizer_dense
     product:
       nb: output/vectorizer_dense.ipynb
     params:
       random_seed: 42

   - source: category_classification_models.py
     name: category_classification_models
     product:
       nb: output/category_classification_models.ipynb
       model_lr: output/model_lr.pkl
       model_rf: output/model_rf.pkl
       model_nb: output/model_nb.csv
       model_votingc: output/model_votingc.csv
     params:
       random_seed: 42

   - source: recent_tweets.py
     name: recent_tweets_wildfire
     product:
       nb: output/recent_tweets_wildfire.ipynb
       file: output/recent_tweets_wildfire.csv
     params:
       disaster_type: Wildfire
       query: "wildfire (donate OR (dead toll) OR burn OR fire OR forest OR damage)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_earthquake
     product:
       nb: output/recent_tweets_earthquake.ipynb
       file: output/recent_tweets_earthquake.csv
     params:
       disaster_type: Earthquake
       query: "earthquake (pray OR victim OR donate OR resque OR damage OR magnitude)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_flood
     product:
       nb: output/recent_tweets_flood.ipynb
       file: output/recent_tweets_flood.csv
     params:
       disaster_type: Flood
       query: "flood (relief OR water OR donate OR (dead toll) OR resque OR destroy)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

   - source: recent_tweets.py
     name: recent_tweets_hurricane
     product:
       nb: output/recent_tweets_hurricane.ipynb
       file: output/recent_tweets_hurricane.csv
     params:
       disaster_type: Hurricane
       query: "hurricane (donate OR storm OR cyclone OR damage OR evacuation OR destroy)"
       language: '{{query_language}}'
       limit: 2000
       skip_interval_hours: 2
       credentials_file: '{{credentials_file}}'

#   - source: tweets_timeline.py
#     name: tweets_timeline_fire
#     product:
#       nb: output/tweets_timeline_fire.ipynb
#     params:
#       random_seed: 42

